export const defaultState = {
  parallelCars: 500,
  levels: [6, 4],
  cars: [],
  road: null,
  bestBrain: null,
  trafficOptions: [
    { lane: 1, height: -100 },
    { lane: 0, height: -300 },
    { lane: 2, height: -300 },
    { lane: 0, height: -500 },
    { lane: 1, height: -600 },
    { lane: 2, height: -700 },
    { lane: 2, height: -800 },
    { lane: 1, height: -800 },
    { lane: 0, height: -900 },
  ],
  traffic: [],
  hiddenLayers: [6, 4],
};
